import { CartProvider } from "@/context/ProdCxt";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UV Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <main>
            <Navbar />
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
